on:
  workflow_dispatch:
name: Render video manually
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: node getMusicFromTiktok.js
      - name: create env file
        run: |
            touch .env
            echo OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }} >> .env
      - run: npm run build
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - uses: actions/upload-artifact@v2
        with:
          name: video.mp4
          path: out/video.mp4
